### ISSUE TITLE
Use PATCH or apply to update resources

### ISSUE THREAD

**Issue by ant31** [coreos/kpm#26]
Currently kpm replace the resource (delete/create). 
Performing a PATCH seems a better default. 

To keep the previous behavior (replace) available add a key in the manifest:

```
resources:
  - name: kube-ui-rc.yaml
    type: rc
    strategy: replace  

- name: resource.yaml
  type: deployment
  strategy: update   # Default  behavior
```
