### ISSUE TITLE
Shard count

### ISSUE THREAD

**Issue by ant31** [coreos/kpm#34]
proposal :
```
shardcount: 5
shards:
   - name: {{i}}
```

another one would e to transform shards into a hash:, and name shard list

```
resources:
  - name: etcd
    file: etcd-rc.yaml
    sharded: [new, existing]

shards:
  new:  
     count: 0..3
     nodes: 
         -  name: node{i} 
  existing:
     count: 3..5
         - name: node{i}
```
