### ISSUE TITLE
Use the package variable in the dependencies

### ISSUE THREAD

**Issue by ant31** [coreos/kpm#46]
i.e: 

```
variables:
  name:  foo

deploy:
  - name: titi/lala
    variables:
        user:  {{$self.name}}
```
