### ISSUE TITLE
Create an ansible module for kpm

### ISSUE THREAD

**Issue by ant31** [coreos/kpm#52]
proposal: 
```yaml
tasks:
  - name: deploy app
    kpm: package=ant31/ghost namespace=titi state=present
```
