### ISSUE TITLE
Deploy multiple applications natively

### ISSUE THREAD

**Issue by rodcloutier** [coreos/kpm#61]
It would be nice to be able to use a file to define multiple applications and the associated command to use it.
Something similar to pip requirements files.

**Comment by ant31** [comment]
Hi, 
You can list required/dependencies application the 'deploy' section of the manifest

Here an example of a 'meta-package' that only regroup a list of application in one another package

https://github.com/kubespray/kpm-packages/blob/master/ant31/op-tools/manifest.yaml

```yaml
---
package:
  name: ant31/op-tools
  author: Antoine Legrand
  version: 1.0.0
  description: Deploy my Kubernetes monitoring tools
  license: MIT

deploy:
  - name: kube-system/heapster
  - name: kube-system/influxdb-grafana
  - name: kube-system/kubernetes-dashboard
  - name: kube-system/kubedash
  - name: kube-system/kube-ui
```

this is the manifest for the package `ant31/op-tools`, it deploys  heaspter,grafana,dashboard,kubedash,kube-ui

the command to deploy all those 5 apps is :
`kpm deploy ant31/op-tools`

Similary you can create any package you want with the list of required applications 

Does it answer you issue or did I misunderstood it ?
